ALTER TABLE "Artist" ADD COLUMN "isArchived" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Place" ADD COLUMN "isArchived" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "SurveyResponse" ADD COLUMN "isArchived" BOOLEAN NOT NULL DEFAULT false;
